services:
  odoo:
    image: odoo:19
    command: ["odoo", "--dev=reload,xml,werkzeug"]
    depends_on: [ db ]
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADDONS_PATH=/mnt/extra-addons
    networks:
      veridata.network:
        aliases:
          - veridata.odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      veridata.network:
        aliases:
          - veridata.odoodb
volumes:
  odoo-data:
  db-data:

networks:
  veridata.network:
    external: true
